<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistPhpSpecTestResultParser' => 'src/parser/ArcanistPhpSpecTestResultParser.php',
    'PhpSpecUnitTestEngine' => 'src/engine/PhpSpecUnitTestEngine.php',
  ),
  'function' => array(),
  'xmap' => array(
    'ArcanistPhpSpecTestResultParser' => 'ArcanistTestResultParser',
    'PhpSpecUnitTestEngine' => 'ArcanistUnitTestEngine',
  ),
));
